### ISSUE TITLE
AssertionError: COLOR_FILE doesnt exist

### ISSUE THREAD

**Issue by B1ackg0d** [riven314/pyqt_speed_test#1]
Hi，I want to run your project，but I have a problem：AssertionError: COLOR_FILE doesnt exist.
I think I can't find these files color150.mat...Can you help me.
```
        self.COLOR_FILE = os.path.join(self.ROOT, 'data', 'color150.mat')
        self.COLOR2OBJ_FILE = os.path.join(self.ROOT, 'data', 'object150_info.csv')
        self.CFG_FILE = os.path.join(self.ROOT, 'config', 'ade20k-mobilenetv2dilated-c1_deepsup.yaml')
```

**Comment by riven314** [comment]
Hi @B1ackg0d 
This repo has been deprecated and migrated to [DeepLearning-Navigation](https://github.com/riven314/DeepLearning-Navigation)
I have just added the files that you need in that repo ([here is the pointer](https://github.com/riven314/DeepLearning-Navigation/tree/master/mobilenet_segment/data))
Hope it helps

**Comment by B1ackg0d** [comment]
Thanks a million！Could you tell me more about use torch model training in pyqt thread, encounter high CPU usage.
I think the thread is waiting for the result of the model, and the CPU is busy waiting.I'm not sure, is it the problem of pyqt or the problem of pytorch's model, because pytorch multi-threaded data loading may also cause high CPU...QAQ
Thank you so much again, I thought I couldn't wait for your reply.

**Comment by riven314** [comment]
It has been a long time ago when I worked on this project
From what I can best recall, high CPU usage is expected, after all segmentation model is computationally expensive.
I didnt use pyqt for model training though. I did model inference only in pyqt. You could refer to this script for how I handled PyQT threading and how I did model inference: 
https://github.com/riven314/DeepLearning-Navigation/blob/master/thread_utils.py

**Comment by B1ackg0d** [comment]
Thank you very much! In fact, I also do model inference（It was a slip of the tongue）, but the CPU usage reached 100%, I think there must be a problem. I will study your code seriously. Good night!

**Comment by riven314** [comment]
@B1ackg0d 
From my experience, the CPU usage could be as high as 100%. To reduce CPU usage/ speed up, you can try resizing frames into smaller ones before feeding it into the model. 
I will close this issue thread coz the main issue (i.e. missing files) has been addressed, but in case you have additional questions, feel free to raise here/ open a new issue thread.
